# Acknowledgments {-}

The Climate Lab Incubation Program constitutes an original work that comes from the valuable contribution from multiple people and institutions. In these few lines we would like to acknowledge and thank them for their time and support. 


- To Laure Morel, Laurent Dupont, Giovanny Arbelaez and Maxence Arnould from ENSGSI School and the ERPI Laboratory from Université de Lorraine for contributing to this program with their knowledge and research experience
- To the student association GSI Media from the ENSGSI School for their support in editing the conceptual videos
- To Valeria Gonzalez and the Universidad de Caldas for producing and editing the case experience videos
- To Lorena Delgado and the Universidad Santiago de Chile for sharing the journey of their innovation lab the LEIND
- To Mark Andersson and the Glasgow Caledonian University for presenting their experience in supporting social innovation initiatives around the world
- To Paola Alfaro d'Alençon from TU Berlin and Università di Genova for her participation in the conversation around Climate Change
- To Gabriela Carrasco from Ashoka and 2811 for contributing with their experience in Social Entrepreneurship and Innovation
- To all the members of the Climate Lab Consortium for contributing to case experience videos

