# Funding, Partnerships & Opportunities {.unnumbered}

## Erasmus+ {.unnumbered}

Erasmus+ is the EU program to support education, training, youth, and sport in Europe. For the period 2021-2027, the program places particular emphasis on social inclusion, green and digital transitions, and promoting the participation of young people in democratic life.

::: {.infobox .tip data-latex="{.assignment}"}
**NOTICE!**

Capacity-building projects in the field of higher education are transnational cooperation projects, based on multilateral partnerships, primarily between higher education institutions from Programme and eligible Partner Countries.

**Next deadlines: Sept 2021**

-   <https://ec.europa.eu/programmes/erasmus-plus/about_es>

-   <https://ec.europa.eu/programmes/erasmus-plus/opportunities/organisations/innovation-good-practices/capacity-building-higher-education_en>
:::

## Department of State US {.unnumbered}

The U.S. Department of State leads America's foreign policy through diplomacy, advocacy, and assistance. The U.S. Department of State's Bureau of Educational and Cultural Affairs (ECA) works to build friendly, peaceful relations between the people of the United States and the people of other countries through academic, cultural, sports, and professional exchanges, as well as public - private partnerships.

## Trasaplantic {.unnumbered}

Trans-Atlantic Platform for Social Sciences and Humanities (T-AP) is collaboration between humanities and social science research funders from South America, North America and Europe. T-AP aims to enhance the ability of funders, research organizations and researchers to engage in transnational dialogue and collaboration.

-   <https://transatlanticplatform.com/>

## Water Resources Institute {.unnumbered}

The Water Resources Institute is an academic partnership with the Southern California communities we serve driven by the vision that sustaining water resources rests on sound research, analysis and public policy collaboration.

-   <https://www.csusb.edu/water-resources-institute>

## Scotiabank {.unnumbered}

Scotiabank is a leading bank in Canada and a leading financial services provider in the Americas. Their approach to managing environmental, social, and governance (ESG) issues focuses on enabling stakeholders to reach their fullest potential, mobilizing finance to address important social and environmental challenges, and building trust by acting with integrity.

-   <https://www.scotiabank.com/ca/en/about/responsibility-impact/climate-commitments.html>

## Minciencias {.unnumbered}

Administrative Department of Science, Technology, and Innovation in Colombia.

::: {.infobox .tip data-latex="{.assignment}"}
**NOTICE!**

Open call Social construction of knowledge for climate change management.

**Deadline: 15/09/21**

-   <https://minciencias.gov.co/convocatorias/apropiacion-social-del-conocimiento/convocatoria-ideas-para-el-cambio-construccion>
:::

## Fundaci贸n Luker {.unnumbered}

Fundaci贸n Luker was created by the founders of CasaLuker in Manizales in 1994. Casa Luker is a company with over 100 years of tradition in the city and Colombia. Fundaci贸n Luker is a laboratory of social innovation that creates solutions that promote development and equity through public, private, and academic partnerships.

-   <https://fundacionluker.org.co/>

## UN Environment programme {.unnumbered}

The United Nations Environment Programme (UNEP) is the leading global environmental authority that sets the global environmental agenda, promotes the coherent implementation of the environmental dimension of sustainable development within the United Nations system, and serves as an authoritative advocate for the global environment.

-   <https://www.unep.org/about-un-environment/funding-and-partnerships>

## WWF {.unnumbered}

WWF is the leading global nature conservation organization. Their actions are focused on six objectives: species, forests, oceans, freshwater, food, and climate, and energy. In addition, they work within three cross-cutting action lines: political and social governance, finance, and markets. WWF engages at all levels, from local to global, creates effective conservation solutions, and works hand in hand with local communities. WWF is a global, independent, multicultural and non-partisan organization.

-   <https://www.wwf.org.co/>

## Bonn Water Network {.unnumbered}

Aims at bundling and representing the Bonn-based capacities for water research, training and policy advice with a focus on international activities but also well established in the German and European contexts. With major international development organizations and renowned research institutions, the Bonn Water Network and its partners also contributes to the global debate on water through sharing new findings, research projects and policy tools.

-   <http://www.bonnwaternetwork.de/>

## FAO {.unnumbered}

The Food and Agriculture Organization (FAO) is a specialized agency of the United Nations that leads international efforts to defeat hunger.

## Food systems {.unnumbered}

FAO supports governments in building inclusive, efficient and sustainable food systems through leadership-driven, market-based action and collaboration, informed by insights and innovation and in alignment with the Sustainable Development Goals. FAO works closely with governments and key actors such as the private sector, civil society organizations, regional economic community organizations and platforms integrating sustainability in its three dimensions (social, economic and environmental) across global, regional and local food systems.

-   <http://www.fao.org/food-systems/en/>

## Water Agenda {.unnumbered}

Among different topics, FAO works to promote coherent approaches to sustainable land and water management. FAO's work in land and water is relevant to several dimensions of sustainable development, such as the governance and management of food production systems; the provision of essential ecosystem services; food security; human health; biodiversity conservation; and the mitigation of, and adaptation to, climate change.

-   <http://www.fao.org/land-water/water/en/>

## IWMI {.unnumbered}

The international water managment institute is a research-for-development (R4D) organization. WMI targets water and land management challenges faced by poor communities in developing countries, and through this contributes towards the achievement of the Sustainable Development Goals (SDGs) of reducing poverty and hunger and maintaining a sustainable environment.

-   <https://www.iwmi.cgiar.org/>

## Green Climate Fund {.unnumbered}

The Green Climate Fund (GCF) -- a critical element of the historic Paris Agreement - is the world's largest climate fund, mandated to support developing countries raise and realize their Nationally Determined Contributions (NDC) ambitions towards low-emissions, climate-resilient pathways.

-   <https://www.greenclimate.fund/>

## Fundation Lemann {.unnumbered}

Their mission is to make Brazil a more just and equitable place by guaranteeing access to high-quality public education for Brazilians of all backgrounds while supporting the development of leaders committed to the social transformation of Brazil.

-   <https://fundacaolemann.org.br/en>

## Nova Escola {.unnumbered}

Nova Escola is a social Education business and the most recognized brand by Basic Education teachers in Brazil. They develop products, services and content that value teachers, facilitate their daily lives and support their careers. Their mission is to strengthen educators to transform Brazilian public education and enable students to develop their full potential.

-   <https://novaescola.org.br/>

## Climate Ventures {.unnumbered}

Climate Ventures is a multi-sector innovation platform with the purpose of accelerating a regenerative and low-carbon economy. Climate Ventures aims to accelerate the emergence and development of innovations. Their mission is to foster in Brazil an ecosystem of people and organizations that support climate entrepreneurship.

-   <https://www.climateventures.co/en/home2>

## DAAD {.unnumbered}

The DAAD is the world's largest funding organisation for the international exchange of students and researchers. The most important responsibilities of the DAAD include granting scholarships, promoting the internationalization activities of German universities and research organisations, strengthening German cultural and language studies abroad and helping developing countries establish productive higher education institutions. The DAAD is also the National Agency for EU Higher Education Cooperation. DAAD Biodiversity is a partnership that aims to strengthen structures in teaching and research at partner institutions in the field of biodiversity, thus supporting the conservation and sustainable use of biodiversity in partner countries.

::: {.infobox .tip data-latex="{.assignment}"}
**NOTICE!**

**Deadline: 17/09/21**

-   <https://www2.daad.de/hochschulen/ausschreibungen/projekte/de/11342-foerderprogramme-finden/?s=1&projektid=57555682>
:::

## Fundaci贸n Botnar {.unnumbered}

Fondation Botnar is a Swiss-based foundation which champions the use of AI and digital technology to improve the health and wellbeing of children and young people in growing urban environments. To achieve this, they support research, catalyse diverse partners, and invest in emerging technologies and scalable solutions globally.

-   <https://www.fondationbotnar.org/about/>

## Carbon Turnaround {.unnumbered}

Carbon Turnaround is a leading consulting and advisory firm committed to the transformation of the economy and society to a net-zero carbon society. They identify and analyse sustainability problems and resource inefficiencies in production processes in order to develop sustainable and profitable solutions.

-   <https://carbon-turn.com/>

-   Herwig A. Ragossnig [ragossnig\@carbon-turn.com](mailto:ragossnig@carbon-turn.com){.email}
